input:
  broker:
    inputs:
      # Source 1: Airplanes.live (Primary)
      - generate:
          interval: "30s" # Relaxed interval to avoid 429s
          mapping: "root = {}"
        processors:
          - http:
              url: "https://api.airplanes.live/v2/point/${LAT}/${LON}/${RADIUS}"
              verb: GET
              headers:
                User-Agent: "SovereignWatch/1.0"
              timeout: 5s
              retries: 1
          - mapping: |
              root.source = "airplanes_live"
              root.data = this

      # Source 2: ADSB.fi (Secondary)
      - generate:
          interval: "30s"
          mapping: "root = {}"
        processors:
          - sleep:
              duration: "10s" # Stagger requests (Uniform 10s cadence)
          - http:
              url: "https://opendata.adsb.fi/api/v3/lat/${LAT}/lon/${LON}/dist/${RADIUS}"
              verb: GET
              headers:
                User-Agent: "SovereignWatch/1.0"
              timeout: 5s
              retries: 1
          - mapping: |
              root.source = "adsb_fi"
              root.data = this

      # Source 3: ADSB.lol (Tertiary)
      - generate:
          interval: "30s"
          mapping: "root = {}"
        processors:
          - sleep:
              duration: "20s" # Stagger requests (Uniform 10s cadence)
          - http:
              url: "https://api.adsb.lol/v2/point/${LAT}/${LON}/${RADIUS}"
              verb: GET
              headers:
                User-Agent: "SovereignWatch/1.0"
              timeout: 5s
              retries: 1
          - mapping: |
              root.source = "adsb_lol"
              root.data = this

pipeline:
  processors:
    # 1. Validation & Array Extraction
    # All APIs return { "ac": [...] } or { "aircraft": [...] } - standardizing
    - mapping: |
        root = if this.data.exists("ac") && this.data.ac.type() == "array" { this.data.ac } else if this.data.exists("aircraft") && this.data.aircraft.type() == "array" { this.data.aircraft } else { deleted() }

    # 2. Flatten Array (One message per aircraft)
    - unarchive:
        format: json_array

    # 3. Filter Invalid Data
    - mapping: |
        root = if this.lat.type() == "null" || this.lon.type() == "null" { deleted() } else { this }

    # 5. TAK Normalization
    - mapping: |
        # Context Check (Exclude T-F-M meta-messages)
        root = if this.r == "T-F-M" { deleted() } else { this }

    - mapping: |
        # Root CoT fields
        root.uid = this.hex
        root.time = now()
        root.start = now()
        root.stale = now()

        # Decoding dbFlags for Type (Placeholder logic)
        let is_mil = false
        # let is_mil = (this.dbFlags.or(0) & 1) == 1 

        root.type = if $is_mil { "a-f-A-M-F" } else { "a-f-A-C-F" }
        root.how = "m-g"

        # Point Data
        root.point.lat = this.lat
        root.point.lon = this.lon
        # ADS-B 'alt_baro' is in feet, convert to meters (HAE)
        root.point.hae = if this.alt_baro == "ground" { 0.0 } else { this.alt_baro.or(0).float64() } * 0.3048
        root.point.ce = 10.0
        root.point.le = 10.0

        # Details
        root.detail.track.course = this.track
        root.detail.track.speed = this.gs.or(0).float64() * 0.514444 # Knots to m/s
        root.detail.contact.callsign = this.flight.trim().or(this.hex)

output:
  kafka:
    addresses: ["sovereign-redpanda:9092"]
    topic: "adsb_raw"
    key: ${! json("uid") }
