# Maritime AIS Ingestion Pipeline (AISStream.io -> TAK Format -> Redpanda)
# Docs: https://aisstream.io/documentation

input:
  websocket:
    url: "wss://stream.aisstream.io/v0/stream"
    # Send subscription message on connect with API key and bounding box
    # Coverage: Oregon coast to Cascades, Eugene to Seattle (~275km)
    open_message: |
      {
        "APIKey": "${AISSTREAM_API_KEY}",
        "BoundingBoxes": [
          [[43.5, -125.5], [47.5, -120.0]]
        ],
        "FilterMessageTypes": ["PositionReport"]
      }

pipeline:
  processors:
    # Parse the incoming JSON
    - mapping: |
        root = this

    # Filter for PositionReport messages only (skip metadata/errors)
    - mapping: |
        root = if this.MessageType == "PositionReport" { this } else { deleted() }

    # Transform to TAK-compatible JSON format
    - mapping: |
        let msg = this.Message.PositionReport
        let meta = this.MetaData

        root.uid = $meta.MMSI.string()
        root.type = "a-f-S-C-M"
        root.how = "m-g"
        root.time = now()
        root.start = now()
        root.stale = now().ts_add_iso8601("PT5M")

        root.point.lat = $msg.Latitude
        root.point.lon = $msg.Longitude
        root.point.hae = 0
        root.point.ce = 10.0
        root.point.le = 10.0

        root.detail.track.course = $msg.Cog.or(0)
        root.detail.track.speed = ($msg.Sog.or(0) * 0.514444)
        root.detail.contact.callsign = $meta.ShipName.or($meta.MMSI.string())

output:
  kafka:
    addresses: ["sovereign-redpanda:9092"]
    topic: "ais_raw"
    key: ${! json("uid") }
