from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
WORLD_COUNTRIES_PATH = ROOT / "frontend" / "public" / "world-countries.json"
COUNTRY_CENTROIDS_PATH = ROOT / "frontend" / "public" / "country_centroids.json"
OVERRIDES_PATH = ROOT / "backend" / "api" / "data" / "gdelt_country_overrides.json"
OUTPUT_PATH = ROOT / "backend" / "api" / "routers" / "gdelt_country_codes.py"


def normalize_country_label(value: str | None) -> str:
    if not value:
        return ""
    chars = [char.lower() if char.isalnum() else " " for char in str(value)]
    return " ".join("".join(chars).split())


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def iter_feature_rings(geometry: dict) -> list[list[list[float]]]:
    geometry_type = geometry.get("type")
    coordinates = geometry.get("coordinates") or []
    if geometry_type == "Polygon":
        return coordinates
    if geometry_type == "MultiPolygon":
        rings: list[list[list[float]]] = []
        for polygon in coordinates:
            rings.extend(polygon)
        return rings
    return []


def build_country_name_map(features: list[dict], manual_names: dict[str, str]) -> dict[str, str]:
    names: dict[str, str] = {}
    for feature in features:
        properties = feature.get("properties", {})
        code = str(properties.get("ISO3166-1-Alpha-3") or "").strip().upper()
        name = properties.get("name")
        if not code or code == "-99" or not name:
            continue
        names[code] = str(name)
    names.update({code.upper(): value for code, value in manual_names.items()})
    return dict(sorted(names.items()))


def build_point_sets(
    features: list[dict],
    code_remaps: dict[str, str],
    valid_codes: set[str],
) -> dict[str, set[tuple[float, float]]]:
    point_sets: dict[str, set[tuple[float, float]]] = {}
    for feature in features:
        properties = feature.get("properties", {})
        raw_code = str(properties.get("ISO3166-1-Alpha-3") or "").strip().upper()
        if not raw_code or raw_code == "-99":
            continue
        code = code_remaps.get(raw_code, raw_code)
        if code not in valid_codes:
            continue
        point_set = point_sets.setdefault(code, set())
        for ring in iter_feature_rings(feature.get("geometry", {})):
            for point in ring:
                if len(point) >= 2:
                    point_set.add((round(float(point[0]), 3), round(float(point[1]), 3)))
    return point_sets


def build_neighbors(
    point_sets: dict[str, set[tuple[float, float]]],
    valid_codes: set[str],
    neighbor_overrides: dict[str, list[str]],
) -> dict[str, set[str]]:
    neighbors: dict[str, set[str]] = {code: set() for code in valid_codes}
    point_items = sorted(point_sets.items())
    for index, (code_a, points_a) in enumerate(point_items):
        for code_b, points_b in point_items[index + 1 :]:
            if len(points_a & points_b) >= 2:
                neighbors[code_a].add(code_b)
                neighbors[code_b].add(code_a)

    for code, extra_neighbors in neighbor_overrides.items():
        code_upper = code.upper()
        if code_upper not in neighbors:
            continue
        for other in extra_neighbors:
            other_upper = other.upper()
            if other_upper not in neighbors:
                continue
            neighbors[code_upper].add(other_upper)
            neighbors[other_upper].add(code_upper)

    return {code: set(sorted(values)) for code, values in sorted(neighbors.items())}


def build_centers(
    centroids: dict[str, list[float]],
    code_remaps: dict[str, str],
    valid_codes: set[str],
) -> dict[str, tuple[float, float]]:
    centers: dict[str, tuple[float, float]] = {}
    for raw_code, coords in centroids.items():
        code = code_remaps.get(str(raw_code).upper(), str(raw_code).upper())
        if code not in valid_codes or not isinstance(coords, list) or len(coords) < 2:
            continue
        centers[code] = (float(coords[0]), float(coords[1]))
    return dict(sorted(centers.items()))


def render_python_module(
    *,
    country_names: dict[str, str],
    normalized_names: dict[str, str],
    code_by_normalized_name: dict[str, str],
    country_centers: dict[str, tuple[float, float]],
    country_neighbors: dict[str, set[str]],
) -> str:
    lines = [
        '"""Static GDELT country linkage data derived from workspace assets."""',
        "",
        "from __future__ import annotations",
        "",
        "# Generated by tools/generate_gdelt_country_codes.py",
        "",
    ]

    def emit_dict(name: str, mapping: dict[str, object]) -> None:
        lines.append(f"{name}: dict[str, object] = {{")
        for key, value in mapping.items():
            lines.append(f"    {key!r}: {value!r},")
        lines.append("}")
        lines.append("")

    emit_dict("COUNTRY_NAME_BY_CODE", country_names)
    emit_dict("COUNTRY_NORMALIZED_NAME_BY_CODE", normalized_names)
    emit_dict("COUNTRY_CODE_BY_NORMALIZED_NAME", code_by_normalized_name)
    emit_dict("COUNTRY_CENTER_BY_CODE", country_centers)

    lines.append("COUNTRY_NEIGHBORS: dict[str, set[str]] = {")
    for code, values in country_neighbors.items():
        ordered = ", ".join(repr(value) for value in sorted(values))
        lines.append(f"    {code!r}: {{{ordered}}},")
    lines.append("}")
    lines.append("")
    lines.append("__all__ = [")
    lines.append("    'COUNTRY_NAME_BY_CODE',")
    lines.append("    'COUNTRY_NORMALIZED_NAME_BY_CODE',")
    lines.append("    'COUNTRY_CODE_BY_NORMALIZED_NAME',")
    lines.append("    'COUNTRY_CENTER_BY_CODE',")
    lines.append("    'COUNTRY_NEIGHBORS',")
    lines.append("]")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    overrides = load_json(OVERRIDES_PATH)
    world = load_json(WORLD_COUNTRIES_PATH)
    centroids = load_json(COUNTRY_CENTROIDS_PATH)

    code_remaps = {
        str(key).upper(): str(value).upper() for key, value in overrides.get("code_remaps", {}).items()
    }
    manual_names = {
        str(key).upper(): str(value) for key, value in overrides.get("manual_names", {}).items()
    }
    name_aliases = {
        normalize_country_label(key): str(value).upper()
        for key, value in overrides.get("name_aliases", {}).items()
    }
    neighbor_overrides = {
        str(key).upper(): [str(value).upper() for value in values]
        for key, values in overrides.get("neighbor_overrides", {}).items()
    }

    features = world.get("features", []) if isinstance(world, dict) else []
    country_names = build_country_name_map(features, manual_names)
    valid_codes = set(country_names)
    point_sets = build_point_sets(features, code_remaps, valid_codes)
    country_neighbors = build_neighbors(point_sets, valid_codes, neighbor_overrides)
    country_centers = build_centers(centroids, code_remaps, valid_codes)

    normalized_names = {
        code: normalize_country_label(name) for code, name in country_names.items()
    }
    code_by_normalized_name = {
        value: code for code, value in normalized_names.items() if value
    }
    for alias, code in sorted(name_aliases.items()):
        if alias and code in valid_codes:
            code_by_normalized_name.setdefault(alias, code)

    module_text = render_python_module(
        country_names=country_names,
        normalized_names=normalized_names,
        code_by_normalized_name=dict(sorted(code_by_normalized_name.items())),
        country_centers=country_centers,
        country_neighbors=country_neighbors,
    )
    OUTPUT_PATH.write_text(module_text, encoding="utf-8")


if __name__ == "__main__":
    main()