# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/tak.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/tak.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fproto/tak.proto\x12\ttak.proto\"3\n\nTakMessage\x12%\n\x08\x63otEvent\x18\x01 \x01(\x0b\x32\x13.tak.proto.CotEvent\"\xc0\x01\n\x08\x43otEvent\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\r\n\x05start\x18\x03 \x01(\x04\x12\r\n\x05stale\x18\x04 \x01(\x04\x12\x0c\n\x04time\x18\x05 \x01(\x04\x12\x0b\n\x03how\x18\x06 \x01(\t\x12\x0b\n\x03lat\x18\x07 \x01(\x01\x12\x0b\n\x03lon\x18\x08 \x01(\x01\x12\x0b\n\x03hae\x18\t \x01(\x01\x12\n\n\x02\x63\x65\x18\n \x01(\x01\x12\n\n\x02le\x18\x0b \x01(\x01\x12!\n\x06\x64\x65tail\x18\x0c \x01(\x0b\x32\x11.tak.proto.Detail\"\xde\x01\n\x06\x44\x65tail\x12#\n\x07\x63ontact\x18\x01 \x01(\x0b\x32\x12.tak.proto.Contact\x12\x1f\n\x05track\x18\x02 \x01(\x0b\x32\x10.tak.proto.Track\x12\x1f\n\x05group\x18\x03 \x01(\x0b\x32\x10.tak.proto.Group\x12!\n\x06status\x18\x04 \x01(\x0b\x32\x11.tak.proto.Status\x12\x37\n\x11precisionLocation\x18\x05 \x01(\x0b\x32\x1c.tak.proto.PrecisionLocation\x12\x11\n\txmlDetail\x18\x64 \x01(\t\"-\n\x07\x43ontact\x12\x10\n\x08\x63\x61llsign\x18\x01 \x01(\t\x12\x10\n\x08\x65ndpoint\x18\x02 \x01(\t\"5\n\x05Track\x12\x0e\n\x06\x63ourse\x18\x01 \x01(\x01\x12\r\n\x05speed\x18\x02 \x01(\x01\x12\r\n\x05slope\x18\x03 \x01(\x01\"#\n\x05Group\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\",\n\x06Status\x12\x0f\n\x07\x62\x61ttery\x18\x01 \x01(\r\x12\x11\n\treadiness\x18\x02 \x01(\x08\"8\n\x11PrecisionLocation\x12\x13\n\x0bgeopointsrc\x18\x01 \x01(\t\x12\x0e\n\x06\x61ltsrc\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.tak_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TAKMESSAGE']._serialized_start=30
  _globals['_TAKMESSAGE']._serialized_end=81
  _globals['_COTEVENT']._serialized_start=84
  _globals['_COTEVENT']._serialized_end=276
  _globals['_DETAIL']._serialized_start=279
  _globals['_DETAIL']._serialized_end=501
  _globals['_CONTACT']._serialized_start=503
  _globals['_CONTACT']._serialized_end=548
  _globals['_TRACK']._serialized_start=550
  _globals['_TRACK']._serialized_end=603
  _globals['_GROUP']._serialized_start=605
  _globals['_GROUP']._serialized_end=640
  _globals['_STATUS']._serialized_start=642
  _globals['_STATUS']._serialized_end=686
  _globals['_PRECISIONLOCATION']._serialized_start=688
  _globals['_PRECISIONLOCATION']._serialized_end=744
# @@protoc_insertion_point(module_scope)
